#pragma once

// HARDWARE PINS

#define MOTOR1_ENABLE (27)
#define MOTOR1_PHASE (26)

#define MOTOR2_ENABLE (21)
#define MOTOR2_PHASE (20)

#define MOTOR3_ENABLE (19)
#define MOTOR3_PHASE (18)

#define MOTOR4_ENABLE (17)
#define MOTOR4_PHASE (16)

#define SERVO1_PIN (15)
#define SERVO2_PIN (14)
#define SERVO3_PIN (13)
#define SERVO4_PIN (12)

#define RADIO_LED_PIN (28)

#define ULTRASONIC_TRIG_PIN (4)
#define ULTRASONIC_ECHO_PIN (5)

const int LINE_SENSOR_PINS[] = { 6, 7, 8, 9, 10, 11 };

// CONFIGURED PINS

#define DRIVETRAIN_LEFT_ENABLE_PIN MOTOR3_ENABLE
#define DRIVETRAIN_LEFT_PHASE_PIN MOTOR3_PHASE
#define DRIVETRAIN_RIGHT_ENABLE_PIN MOTOR4_ENABLE
#define DRIVETRAIN_RIGHT_PHASE_PIN MOTOR4_PHASE

#define ELEVATOR_ENABLE_PIN MOTOR3_ENABLE // TODO: find correct pin
#define ELEVATOR_PHASE_PIN MOTOR3_PHASE // TODO: find correct pin

#define PUSHER_SERVO_PIN SERVO1_PIN
