#pragma once

// LOGGING

#define CONTROLLER_LOGGING_ENABLED false
#define LINE_SENSOR_LOGGING_ENABLED false
#define DRIVETRAIN_LOGGING_ENABLED false
#define ELEVATOR_LOGGING_ENABLED false
#define GATE_LOGGING_ENABLED false
#define SONAR_LOGGING_ENABLED true

// SUBSYSTEMS

#define DRIVETRAIN_LINEAR_DEADBAND 0.05
#define DRIVETRAIN_ANGULAR_DEADBAND 0.05

#define GATE_CLOSE_ANGLE 0
#define GATE_OPEN_ANGLE 0

#define WHITE_THRESHOLD 500
#define BLACK_THRESHOLD 2500

// LINE FOLLOWING

#define LINE_FOLLOWING_LINEAR_SPEED 0.2
#define LINE_FOLLOWING_ANGULAR_MULTIPLIER 0.2

// DRIVER CONTROLS

#define DRIVER_LINEAR_DEADBAND 0.15
#define DRIVER_ANGULAR_DEADBAND 0.15
