#pragma once

// LOGGING

#define CONTROLLER_LOGGING_ENABLED false
#define DRIVETRAIN_LOGGING_ENABLED false
#define SHOULDER_LOGGING_ENABLED false
#define ARM_LOGGING_ENABLED false

// SUBSYSTEMS

#define DRIVETRAIN_LINEAR_DEADBAND 0.05
#define DRIVETRAIN_ANGULAR_DEADBAND 0.05

#define PUSHER_RETRACTED_ANGLE 63
#define PUSHER_EXTENDED_ANGLE 0


#define SHOULDER_STOW_ANGLE 0

#define SHOULDER_READY_PICKUP_ANGLE 0
#define SHOULDER_ACTIVE_PICKUP_ANGLE 0

#define SHOULDER_LEVEL_3_READY_ANGLE 0
#define SHOULDER_LEVEL_3_SCORE_ANGLE 0

#define SHOULDER_LEVEL_2_READY_ANGLE 0
#define SHOULDER_LEVEL_2_SCORE_ANGLE 0

#define SHOULDER_LEVEL_1_READY_ANGLE 0
#define SHOULDER_LEVEL_1_SCORE_ANGLE 0


#define WRIST_STOW_ANGLE 0

#define WRIST_READY_PICKUP_ANGLE 0
#define WRIST_ACTIVE_PICKUP_ANGLE 0

#define WRIST_LEVEL_3_READY_ANGLE 0
#define WRIST_LEVEL_3_SCORE_ANGLE 0

#define WRIST_LEVEL_2_READY_ANGLE 0
#define WRIST_LEVEL_2_SCORE_ANGLE 0

#define WRIST_LEVEL_1_READY_ANGLE 0
#define WRIST_LEVEL_1_SCORE_ANGLE 0


// DRIVER CONTROLS

#define DRIVER_LINEAR_DEADBAND 0.15
#define DRIVER_ANGULAR_DEADBAND 0.15
