#pragma once

// LOGGING

#define CONTROLLER_LOGGING_ENABLED false
#define LINE_SENSOR_LOGGING_ENABLED false
#define DRIVETRAIN_LOGGING_ENABLED false
#define ELEVATOR_LOGGING_ENABLED false
#define GATE_LOGGING_ENABLED false

// SUBSYSTEM SETTINGS

#define DRIVETRAIN_LINEAR_DEADBAND 0.1
#define DRIVETRAIN_ANGULAR_DEADBAND 0.1

#define GATE_CLOSE_ANGLE 0
#define GATE_OPEN_ANGLE 0

// DRVIER SETTINGS

#define DRIVER_LINEAR_DEADBAND 0.15
#define DRIVER_ANGULAR_DEADBAND 0.15
